// Mocks generated by Mockito 5.4.2 from annotations
// in pipoca_filmes/test/domain/usecases/get_popular_movies_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pipoca_filmes/domain/entities/movie_entity.dart' as _i4;
import 'package:pipoca_filmes/domain/repositories/movie_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  @override
  _i3.Future<List<_i4.MovieEntity>> getTrendingMoviesList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingMoviesList,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
      ) as _i3.Future<List<_i4.MovieEntity>>);
  @override
  _i3.Future<List<_i4.MovieEntity>> searchMovies(String) => (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
      ) as _i3.Future<List<_i4.MovieEntity>>);
  @override
  _i3.Future<List<_i4.MovieEntity>> getPopularMoviesList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMoviesList,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.MovieEntity>>.value(<_i4.MovieEntity>[]),
      ) as _i3.Future<List<_i4.MovieEntity>>);
}
